FROM python:3

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --proxy http://10.0.9.24:8080  --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD [ "python", "./prometheus.py" ]
